apiVersion: v1
entries:
  apisix:
  - apiVersion: v2
    appVersion: "1.2"
    created: "2020-08-25T10:50:46.689587158+08:00"
    description: A Helm chart for apisix using Kubernetes
    digest: 256c7dc5b0c4b32d88b6510191f0060440754ad58dc58ec9feaddfcfc8b91518
    home: https://github.com/scott-wong/helm-charts/apisix
    keywords:
    - apisix
    - api gateway
    name: apisix
    type: application
    urls:
    - https://scott-wong.ga/charts/apisix-0.1.1.tgz
    version: 0.1.1
  cmak:
  - apiVersion: v2
    appVersion: 3.0.0.4
    created: "2020-08-25T10:50:46.69009406+08:00"
    description: A Helm chart for CMAK
    digest: 6373cad68440115946bcfb4b43bd83f77cf1917410366472813b0a4ba345c07a
    home: https://github.com/scott-wong/helm-charts/cmak
    keywords:
    - kafka
    - cmak
    name: cmak
    type: application
    urls:
    - https://scott-wong.ga/charts/cmak-0.1.1.tgz
    version: 0.1.1
  kong:
  - apiVersion: v1
    appVersion: "2"
    created: "2020-08-25T10:50:46.695170294+08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 8.6.8
    description: The Cloud-Native Ingress and API-management
    digest: 11a4399316f5f66fd9f8105c29a8d6f86a8fce3f04c5b98fbb0bb1307a8851ad
    home: https://konghq.com/
    icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
    maintainers:
    - email: harry@konghq.com
      name: hbagdi
    - email: traines@konghq.com
      name: rainest
    name: kong
    urls:
    - https://scott-wong.ga/charts/kong-1.5.0.tgz
    version: 1.5.0
  konga:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-08-25T10:50:46.695594722+08:00"
    description: A Helm chart for Kubernetes
    digest: 50967202becb84f8e5e42af6575134b9267c421e1728b35780c3894791b1b8d5
    name: konga
    urls:
    - https://scott-wong.ga/charts/konga-1.0.0.tgz
    version: 1.0.0
  nacos:
  - apiVersion: v2
    appVersion: 1.3.2
    created: "2020-08-25T10:50:46.696733798+08:00"
    description: A Nacos Helm chart for Kubernetes
    digest: 94c28338471bc045d097839e2b51d80a941090c5fbca5055cd6411bd4df77de1
    home: https://github.com/scott-wong/helm-charts/nacos
    icon: https://scott-wong.github.io/charts/icons/nacos_colorful.png
    keywords:
    - nacos
    maintainers:
    - name: scott-wong
    name: nacos
    type: application
    urls:
    - https://scott-wong.ga/charts/nacos-1.0.1.tgz
    version: 1.0.1
generated: "2020-08-25T10:50:46.687757264+08:00"
