apiVersion: v1
entries:
  apisix:
  - apiVersion: v2
    appVersion: "1.2"
    created: "2020-07-22T17:41:00.332514975+08:00"
    description: A Helm chart for apisix using Kubernetes
    digest: 32dc3d43bed3d3b2d537a609383c200a2b9a5a8bdb86a45a5f6883999223b9de
    home: https://github.com/scott-wong/helm-charts/apisix
    keywords:
    - apisix
    - api gateway
    name: apisix
    type: application
    urls:
    - https://scott-wong.github.io/charts/apisix-0.1.1.tgz
    version: 0.1.1
  cmak:
  - apiVersion: v2
    appVersion: 3.0.0.4
    created: "2020-07-22T17:41:00.33298189+08:00"
    description: A Helm chart for CMAK
    digest: 3c455fbbd22957b6eeb036b6fe64676d5f8bff8fee3d221c79ee194f66720fdd
    home: https://github.com/scott-wong/helm-charts/cmak
    keywords:
    - kafka
    - cmak
    name: cmak
    type: application
    urls:
    - https://scott-wong.github.io/charts/cmak-0.1.1.tgz
    version: 0.1.1
  kong:
  - apiVersion: v1
    appVersion: "2"
    created: "2020-07-22T17:41:00.338012982+08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 8.6.8
    description: The Cloud-Native Ingress and API-management
    digest: 684f54760dcb2acf5d2c1fa2d11f689081d81e1796f9a4b7be80e999bbf20b36
    home: https://konghq.com/
    icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
    maintainers:
    - email: harry@konghq.com
      name: hbagdi
    - email: traines@konghq.com
      name: rainest
    name: kong
    urls:
    - https://scott-wong.github.io/charts/kong-1.5.0.tgz
    version: 1.5.0
  konga:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-07-22T17:41:00.338444596+08:00"
    description: A Helm chart for Kubernetes
    digest: 7ae523183b1c40267f00e31971bcaaae5846666890681f29fa6359569bc3c221
    name: konga
    urls:
    - https://scott-wong.github.io/charts/konga-1.0.0.tgz
    version: 1.0.0
  nacos:
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2020-07-22T17:41:00.339420775+08:00"
    description: A Nacos Helm chart for Kubernetes
    digest: cda0c1caed2b1b6c985ee9a0ff2bc31f953e985d5f594acea21999158a52c65b
    home: https://github.com/scott-wong/helm-charts/nacos
    icon: https://scott-wong.github.io/charts/icons/nacos_colorful.png
    keywords:
    - nacos
    maintainers:
    - name: scott-wong
    name: nacos
    type: application
    urls:
    - https://scott-wong.github.io/charts/nacos-1.0.0.tgz
    version: 1.0.0
generated: "2020-07-22T17:41:00.331097724+08:00"
